# Generated by Django 3.2.8 on 2021-11-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0002_rename_neighbourhood_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='updated_at',
        ),
    ]
