# Generated by Django 3.2.8 on 2021-11-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0003_auto_20211101_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
