# Generated by Django 3.2.8 on 2021-11-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0007_auto_20211102_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='neighbourhood',
            new_name='neighborhood',
        ),
    ]
